### ISSUE TITLE
Default background image disappearing on the widgets while fanarts disabled.

### ISSUE THREAD

**Issue by queeup** [osmc/skin.osmc#427]
I updated latest release (19.1.3) and default background image disappearing on the widgets while fanarts disabled.

Reproduce:
1. Disable fanarts from skin settings
2. Browse main screen widgets (TV or Movies).

**Comment by Ch1llb0** [comment]
I can reproduce. Thx for pointing this out! Will try and look for a fix 👍🏻

**Comment by Ch1llb0** [comment]
Hi

Hopefully the issue is now addressed with the following commit: https://github.com/osmc/skin.osmc/commit/6bcdc73eb33ec1adb3d4a844d1ca3612e9f010c6

I'd appreciate it if you could test this and provide feedback before we potentially release this as an update to other users. To test this update:

1. [Login via the command line](https://osmc.tv/wiki/general/accessing-the-command-line/)
2. Run the following command to add the staging repository:
```echo 'deb http://apt.osmc.tv bullseye-devel main' | sudo tee /etc/apt/sources.list.d/osmc-devel.list```
3. Run the following commands to update: ```sudo apt-get update && sudo apt-get dist-upgrade && reboot```
4. Your system should have have received the update. 

Please see if the issue is resolved.

I also recommend you remove ```/etc/apt/sources.list.d/osmc-devel.list``` after updating. 

This will deactivate the staging repository. You can do so with the following command:
```sudo rm /etc/apt/sources.list.d/osmc-devel.list```.

**Comment by queeup** [comment]
Fixed the issue. Thank you.

My way of test is:
```bash
LibreELEC:~ # cd .kodi/addons/skin.osmc/
LibreELEC:~/.kodi/addons/skin.osmc # wget https://github.com/osmc/skin.osmc/commit/6bcdc73eb33ec1adb3d4a844d1ca3612e9f010c6.diff
Connecting to github.com (140.82.121.3:443)
saving to '6bcdc73eb33ec1adb3d4a844d1ca3612e9f010c6.diff'
6bcdc73eb33ec1adb3d4 100% |**********************************************************************************| 10977  0:00:00 ETA
'6bcdc73eb33ec1adb3d4a844d1ca3612e9f010c6.diff' saved
LibreELEC:~/.kodi/addons/skin.osmc # patch -p1 < 6bcdc73eb33ec1adb3d4a844d1ca3612e9f010c6.diff 
patching file xml/Includes_Windows_Dialogs.xml
LibreELEC:~/.kodi/addons/skin.osmc # kodi-send --action="ReloadSkin()"
```
